version: "3.7"

services:
    web:
        build: ./services/web
        command: python manage.py run -h 0.0.0.0 -p 5005
        ports:
            - 5005:5005
        env_file:
            - ./.env
        read_only: true
    robots:
        build: ./services/robots
        command: python manage.py run -h 0.0.0.0 -p 5006
        ports:
            - 5006:5006
        env_file:
            - ./.env
        read_only: true
    source:
        build: ./services/source
        command: python manage.py run -h 0.0.0.0 -p 5007
        ports:
            - 5007:5007
        env_file:
            - ./.env
        read_only: true
    command_injection:
        build: ./services/command_injection
        command: python manage.py run -h 0.0.0.0 -p 5008
        ports:
            - 5008:5008
        env_file:
            - ./.env
        read_only: true
