version: "3.7"

services:
    web:
        build: ./services/web
        command: python manage.py run -h 0.0.0.0 -p 5005
        ports:
            - 5005:5005
        env_file:
            - ./.env
        read_only: true
